name: node-alpine-test

on: [push]

env:
  IMAGE_NAME: ${{ secrets.HUB_REGISTRY }}/hardened-node-alpine
  DOCKER_CONTENT_TRUST: 1
  BASE_IMAGE: node:alpine

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Changed to false to build but not push
          tags: ${{ env.IMAGE_NAME }}:latest
          load: true # Needed to load the built image into Docker's image store for scanning

      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@vmaster
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          exit-code: '1' # Fail the job if vulnerabilities are found
          severity: HIGH,CRITICAL 







# name: Build and Scan

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Build Docker image
#       run: docker build -t my-image .

#     - name: Run trivy scanner
#       uses: aquasecurity/trivy-action@master
#       with:
#         image-ref: my-image
#         exit-code: 1
#         severity: CRITICAL
#         trivy-opts: "--config ./trivy.yaml"
#         list-all-pkgs: true

# name: Build and Run .NET Core App in Docker

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Create .NET Core App
#       run: |
#         dotnet new console -n MyHelloWorldApp
#       # working-directory: ${{ github.workspace }}  # Specify the directory where you want to create the app
#     # - name: List project directory contents
#     #   run: ls /home/runner/work/dotnet/dotnet/MyHelloWorldApp
#     # - name: Cat MyHelloWorldApp.csproj
#     #   run: cat /home/runner/work/dotnet/dotnet/MyHelloWorldApp/MyHelloWorldApp.csproj
#     # - name: Check current directory
#     #   run: |
#     #     pwd
#     #     ls -al

#     # - name: Clear Docker Cache
#     #   run: docker builder prune -a -f
#     - name: Build and publish Docker image
#       run: docker build -t myapp-image .

#     # - name: Build Docker image
#     #   run: |
#     #     docker build -t myapp-image -f ${{ github.workspace }}/Dockerfile .
#     #   working-directory: ${{ github.workspace }}  # Specify the directory containing your Dockerfile

#     - name: Run Docker container
#       run: |
#         docker run myapp-image
#       # working-directory: ${{ github.workspace }}

