# # This is a basic workflow to help you get started with Actions

# name: Build and Scan

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Build Docker image
#       run: docker build -t my-image .

#     - name: Run trivy scanner
#       uses: aquasecurity/trivy-action@master
#       with:
#         image-ref: my-image
#         exit-code: 1
#         severity: CRITICAL
#         trivy-opts: "--config ./trivy.yaml"
#         list-all-pkgs: true

name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        # Navigate to the directory containing your Dockerfile
        cd ${{ github.workspace }}
        docker build -t myapp-image .
      working-directory: ${{ github.workspace }}

    - name: Run Docker container
      run: |
        # Navigate to the directory containing your Dockerfile
        cd ${{ github.workspace }}
        docker run myapp-image
      working-directory: ${{ github.workspace }}