name: Python Performance Test in Ubuntu Container

on: [push]

jobs:
  test-in-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python and Create Virtual Environment
        run: |
          apt-get update
          apt-get install -y python3 python3-venv python3-pip
          python3 -m venv /venv
        shell: bash

      - name: Install pyperformance
        run: |
          source /venv/bin/activate
          pip install pyperformance
        shell: bash

      - name: Run pyperformance Benchmark
        run: |
          source /venv/bin/activate
          pyperformance run --rigorous -b ${{ env.benchmark_list }}
        shell: bash
        env:
          benchmark_list: "depcopy,float"  # Specify benchmarks here



