name: Python Performance Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  benchmark_list: "depcopy, float"

jobs:
  performance_test:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip

    - name: Install pyperformance
      run: python3 -m pip install pyperformance

    - name: Run selected benchmarks
      run: python3 -m pyperformance run --benchmarks ${{ env.benchmark_list }} --affinity=1

