name: Python Performance Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  benchmark_list: "depcopy, float"

jobs:
  performance_test:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install Python and dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-venv python3-pip

    - name: Set up virtual environment
      run: |
        python3 -m venv /venv

    - name: Install pyperformance
      run: |
        source /venv/bin/activate
        pip install pyperformance

    - name: Run selected benchmarks with CPU affinity
      run: |
        source /venv/bin/activate
        pyperformance run --benchmarks ${{ env.benchmark_list }} --affinity=1



