name: Retrieve .NET Version

on:
  push:
    branches:
      - main

jobs:
  get-dotnet-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get .NET Version
      run: |
        CONTAINER_ID=$(docker run -d mcr.microsoft.com/dotnet/runtime:8.0-jammy-chiseled sleep infinity)
        DOTNET_VERSION=$(docker inspect -f '{{range .Config.Env}}{{if (index (split "=" .) 0) "DOTNET_VERSION"}}{{.}}{{end}}{{end}}' $CONTAINER_ID | cut -d'=' -f2)
        echo "The .NET Version is: $DOTNET_VERSION"
        docker stop $CONTAINER_ID

      env:
        DOCKER_CLI_AGGREGATE_OUTPUT: 1